[package]
name = "photomosaic-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
image = "0.24.6"
num_cpus = "1.15.0"
rayon = "1.7"
